"""Filesystem helpers: run-directory layout, JSON/CSV writers, timestamps.

All path handling goes through :mod:`pathlib`. No absolute paths are
hard-coded; everything is anchored to a per-run output directory.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

# Sub-directories created inside every run directory.
RUN_SUBDIRS = ("logs", "intermediate", "commands", "tables")


def utc_timestamp() -> str:
    """Return an ISO-8601 UTC timestamp (second precision)."""

    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def run_id_from_timestamp() -> str:
    """Generate a filesystem-safe run id based on the current UTC time."""

    return datetime.now(timezone.utc).strftime("run_%Y%m%d_%H%M%S")


def ensure_run_dir(output_dir: str | Path) -> Path:
    """Create the run directory and its standard sub-directories.

    Returns the resolved run directory path.
    """

    run_dir = Path(output_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    for sub in RUN_SUBDIRS:
        (run_dir / sub).mkdir(parents=True, exist_ok=True)
    return run_dir


def write_json(path: str | Path, data: Any) -> Path:
    """Serialise *data* to pretty-printed JSON. Returns the written path."""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, default=str)
    return path


def write_csv(path: str | Path, rows: list[dict[str, Any]]) -> Path:
    """Write a list of dict rows to CSV via pandas. Returns the written path.

    An empty ``rows`` list still produces a valid (header-less) file so that
    downstream steps can rely on the file existing.
    """

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(path, index=False)
    return path


def write_text(path: str | Path, text: str) -> Path:
    """Write plain text to *path*. Returns the written path."""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_commands(run_dir: str | Path, name: str, commands: list[str]) -> Path:
    """Persist a list of shell commands to ``<run_dir>/commands/<name>.sh``."""

    path = Path(run_dir) / "commands" / f"{name}.sh"
    header = "#!/usr/bin/env bash\n# Auto-generated by MetaMAVS (dry-run). Review before executing.\nset -euo pipefail\n\n"
    return write_text(path, header + "\n".join(commands) + "\n")
